### ISSUE TITLE
Cannot install using `node server`

### ISSUE THREAD

**Issue by roengle** [fantinodavide/Squad_Whitelister#1]
Using the [v1.1.3 release](https://github.com/fantinodavide/Squad_Whitelister/releases/tag/V1.1.3), running `node server` causes the following error. After the error occurs, `conf.json` is **NOT** created.

Error log:

> node server
Requiring "./package.json"
Requiring "fs-extra"
Requiring "node-stream-zip"
Requiring "https"
Requiring "http"
Requiring "express"
Requiring "path"
Requiring "mongodb"
Requiring "crypto"
Requiring "body-parser"
Requiring "cookie-parser"
Requiring "nocache"
Requiring "log4js"
Requiring "axios"
Requiring "minimist"
Requiring "node-run-cmd"
Requiring "express-force-ssl"
Requiring "find-free-port"
Requiring "process"
Log-file: /home/subuser/whitelister/logs/20220811_210309370.log
Current dir:  /home/subuser/whitelister
Looking for free port close to 80
Uncaught Exception Cannot read properties of undefined (reading 'other') TypeError: Cannot read properties of undefined (reading 'other')
    at /home/subuser/whitelister/server.js:1:1769
    at /home/subuser/whitelister/node_modules/graceful-fs/graceful-fs.js:228:16
    at node:fs:188:23
    at node:internal/util:443:5
    at getDirents (node:internal/fs/utils:276:7)
    at FSReqCallback.req.oncomplete (node:fs:1382:7)
Too many errors occurred during the current run. Terminating execution...
Terminating execution. Process manager will restart me.

**Comment by fantinodavide** [comment]
Issue fixed with beta release 1.1.4. Thank you for reporting the error!
