### ISSUE TITLE
How to Enable Hot Reload

### ISSUE THREAD

**Issue by sfc9982** [fantinodavide/Squad_Whitelister#2]
I want to enablel hot reload while adding new contents, but changes applied on .vue file cant apply to server realtime.

**Comment by fantinodavide** [comment]
Every time you change a .vue file you have to recompile the project. That can be done with `npm run build` or setting up a development environment.

**Comment by sfc9982** [comment]
How to setting up a development environment? I use npm run dev but got a blank page.

**Comment by fantinodavide** [comment]
should be fixed the basic configuration now, try to pull and restart the dev server
